// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using m_motors_API.Data;

#nullable disable

namespace m_motors_API.Migrations
{
    [DbContext(typeof(MMotorsContext))]
    [Migration("20260425134427_InitLLD")]
    partial class InitLLD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Vehicule", b =>
                {
                    b.Property<int>("IdVehicule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vehicule");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVehicule"));

                    b.Property<int?>("Annee")
                        .HasColumnType("int")
                        .HasColumnName("annee");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_ajout");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("Disponible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disponible");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<int?>("Kilometrage")
                        .HasColumnType("int")
                        .HasColumnName("kilometrage");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("marque");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("modele");

                    b.Property<decimal?>("Prix")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("prix");

                    b.Property<string>("TypeOffre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type_offre");

                    b.HasKey("IdVehicule");

                    b.ToTable("vehicule", (string)null);
                });

            modelBuilder.Entity("VehiculeServiceLLD", b =>
                {
                    b.Property<int>("IdVehicule")
                        .HasColumnType("int")
                        .HasColumnName("id_vehicule");

                    b.Property<int>("IdService")
                        .HasColumnType("int")
                        .HasColumnName("id_service");

                    b.HasKey("IdVehicule", "IdService");

                    b.HasIndex("IdService");

                    b.ToTable("vehicule_service_lld", (string)null);
                });

            modelBuilder.Entity("m_motors_API.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_client");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DateUpload");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nom");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telephone");

                    b.HasKey("IdClient");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("m_motors_API.Models.DocumentClient", b =>
                {
                    b.Property<int>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_document");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDocument"));

                    b.Property<string>("CheminFichier")
                        .HasColumnType("longtext")
                        .HasColumnName("chemin_fichier");

                    b.Property<DateTime?>("DateUpload")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_upload");

                    b.Property<int?>("DossierId")
                        .HasColumnType("int")
                        .HasColumnName("dossier_id");

                    b.Property<string>("NomDocument")
                        .HasColumnType("longtext")
                        .HasColumnName("nom_document");

                    b.Property<string>("TypeDocument")
                        .HasColumnType("longtext")
                        .HasColumnName("type_document");

                    b.HasKey("IdDocument");

                    b.HasIndex("DossierId");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("m_motors_API.Models.Dossier", b =>
                {
                    b.Property<int>("IdDossier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_dossier");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDossier"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("statut");

                    b.Property<string>("TypeDossier")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type_dossier");

                    b.Property<int?>("VehiculeId")
                        .HasColumnType("int")
                        .HasColumnName("vehicule_id");

                    b.HasKey("IdDossier");

                    b.HasIndex("ClientId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("dossier", (string)null);
                });

            modelBuilder.Entity("m_motors_API.Models.DossierFinancement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Apport")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("DossierId")
                        .HasColumnType("int")
                        .HasColumnName("dossier_id");

                    b.Property<int?>("Duree")
                        .HasColumnType("int");

                    b.Property<decimal?>("Financement")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("Kilometrage")
                        .HasColumnType("int");

                    b.Property<decimal?>("Mensualite")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.ToTable("dossier_financement", (string)null);
                });

            modelBuilder.Entity("m_motors_API.Models.DossierServiceLLD", b =>
                {
                    b.Property<int>("IdDossier")
                        .HasColumnType("int");

                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.HasKey("IdDossier", "IdService");

                    b.HasIndex("IdService");

                    b.ToTable("dossier_service_lld", (string)null);
                });

            modelBuilder.Entity("m_motors_API.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdRole");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("m_motors_API.Models.ServiceLLD", b =>
                {
                    b.Property<int>("IdService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_service");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdService"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("NomService")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nom_service");

                    b.HasKey("IdService");

                    b.ToTable("service_lld", (string)null);
                });

            modelBuilder.Entity("m_motors_API.Models.SuiviDossier", b =>
                {
                    b.Property<int>("IdSuivi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_suivi");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSuivi"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DossierId")
                        .HasColumnType("int")
                        .HasColumnName("dossier_id");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("IdSuivi");

                    b.HasIndex("DossierId");

                    b.HasIndex("UserId");

                    b.ToTable("suivi_dossier", (string)null);
                });

            modelBuilder.Entity("m_motors_API.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("IdUser");

                    b.HasIndex("RoleId");

                    b.ToTable("utilisateur", (string)null);
                });

            modelBuilder.Entity("VehiculeServiceLLD", b =>
                {
                    b.HasOne("m_motors_API.Models.ServiceLLD", "ServiceLLD")
                        .WithMany("VehiculeServices")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vehicule", "Vehicule")
                        .WithMany("VehiculeServices")
                        .HasForeignKey("IdVehicule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLLD");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("m_motors_API.Models.DocumentClient", b =>
                {
                    b.HasOne("m_motors_API.Models.Dossier", "Dossier")
                        .WithMany("Documents")
                        .HasForeignKey("DossierId");

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("m_motors_API.Models.Dossier", b =>
                {
                    b.HasOne("m_motors_API.Models.Client", "Client")
                        .WithMany("Dossiers")
                        .HasForeignKey("ClientId");

                    b.HasOne("Vehicule", "Vehicule")
                        .WithMany("Dossiers")
                        .HasForeignKey("VehiculeId");

                    b.Navigation("Client");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("m_motors_API.Models.DossierFinancement", b =>
                {
                    b.HasOne("m_motors_API.Models.Dossier", "Dossier")
                        .WithMany("Financements")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("m_motors_API.Models.DossierServiceLLD", b =>
                {
                    b.HasOne("m_motors_API.Models.Dossier", "Dossier")
                        .WithMany("Services")
                        .HasForeignKey("IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("m_motors_API.Models.ServiceLLD", "ServiceLLD")
                        .WithMany()
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");

                    b.Navigation("ServiceLLD");
                });

            modelBuilder.Entity("m_motors_API.Models.SuiviDossier", b =>
                {
                    b.HasOne("m_motors_API.Models.Dossier", "Dossier")
                        .WithMany("Suivis")
                        .HasForeignKey("DossierId");

                    b.HasOne("m_motors_API.Models.Utilisateur", "Utilisateur")
                        .WithMany("Suivis")
                        .HasForeignKey("UserId");

                    b.Navigation("Dossier");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("m_motors_API.Models.Utilisateur", b =>
                {
                    b.HasOne("m_motors_API.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Vehicule", b =>
                {
                    b.Navigation("Dossiers");

                    b.Navigation("VehiculeServices");
                });

            modelBuilder.Entity("m_motors_API.Models.Client", b =>
                {
                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("m_motors_API.Models.Dossier", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Financements");

                    b.Navigation("Services");

                    b.Navigation("Suivis");
                });

            modelBuilder.Entity("m_motors_API.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("m_motors_API.Models.ServiceLLD", b =>
                {
                    b.Navigation("VehiculeServices");
                });

            modelBuilder.Entity("m_motors_API.Models.Utilisateur", b =>
                {
                    b.Navigation("Suivis");
                });
#pragma warning restore 612, 618
        }
    }
}
